/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"

double *
suma_1_svc(entradas *argp, struct svc_req *rqstp)
{
	static double  result;

	printf("El procedimiento Suma ha sido invocado remotamente\n");
	result=argp->x+argp->y;
	printf(" Se realizo: %.2f + %.2f = %.2f\n\n ",argp->x, argp->y, result);
	return &result;
}

double *
resta_1_svc(entradas *argp, struct svc_req *rqstp)
{
	static double  result;

	printf("El procedimiento Resta ha sido invocado remotamente\n");
	result=argp->x-argp->y;
	printf(" Se realizo: %.2f - %.2f = %.2f\n\n ",argp->x, argp->y, result);

	return &result;
}

double *
multiplicacion_1_svc(entradas *argp, struct svc_req *rqstp)
{
	static double  result;
	printf("El procedimiento Multiplicacion ha sido invocado remotamente\n");
	result=argp->x*argp->y;
	printf(" Se realizo: %.2f x %.2f = %.2f\n\n ",argp->x, argp->y, result);

	return &result;
}

double *
division_1_svc(entradas *argp, struct svc_req *rqstp)
{
	static double  result;

	printf("El procedimiento Division ha sido invocado remotamente\n");
	result=argp->x/argp->y;
	printf(" Se realizo: %.2f / %.2f = %.4f\n\n ",argp->x, argp->y, result);

	return &result;
}
