/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULADORA_H_RPCGEN
#define _CALCULADORA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct entradas {
	double x;
	double y;
};
typedef struct entradas entradas;

#define CALCULADORA_PROG 0x31111111
#define CAL_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define SUMA 1
extern  double * suma_1(entradas *, CLIENT *);
extern  double * suma_1_svc(entradas *, struct svc_req *);
#define RESTA 2
extern  double * resta_1(entradas *, CLIENT *);
extern  double * resta_1_svc(entradas *, struct svc_req *);
#define MULTIPLICACION 3
extern  double * multiplicacion_1(entradas *, CLIENT *);
extern  double * multiplicacion_1_svc(entradas *, struct svc_req *);
#define DIVISION 4
extern  double * division_1(entradas *, CLIENT *);
extern  double * division_1_svc(entradas *, struct svc_req *);
extern int calculadora_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SUMA 1
extern  double * suma_1();
extern  double * suma_1_svc();
#define RESTA 2
extern  double * resta_1();
extern  double * resta_1_svc();
#define MULTIPLICACION 3
extern  double * multiplicacion_1();
extern  double * multiplicacion_1_svc();
#define DIVISION 4
extern  double * division_1();
extern  double * division_1_svc();
extern int calculadora_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_entradas (XDR *, entradas*);

#else /* K&R C */
extern bool_t xdr_entradas ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULADORA_H_RPCGEN */
