/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"


void
calculadora_prog_1(char *host, double x, char *operador, double y)
{
	CLIENT *clnt;
	double  *result_1;
	entradas  suma_1_arg;
	double  *result_2;
	entradas  resta_1_arg;
	double  *result_3;
	entradas  multiplicacion_1_arg;
	double  *result_4;
	entradas  division_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, CALCULADORA_PROG, CAL_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	if(*operador == '+'){
		suma_1_arg.x=x;
		suma_1_arg.y=y;
		result_1 = suma_1(&suma_1_arg, clnt);
		if (result_1 == (double *) NULL) {
			clnt_perror (clnt, "call failed");
		}else{
			printf(" RESULTADO \n %.2f + %.2f = %.2f\n ",x,y, *result_1);
		}
		
        }else if(*operador =='-'){
		resta_1_arg.x=x;
		resta_1_arg.y=y;
		result_2 = resta_1(&resta_1_arg, clnt);
		if (result_2 == (double *) NULL) {
			clnt_perror (clnt, "call failed");
		}else{
			printf(" RESULTADO \n %.2f - %.2f = %.2f\n ",x,y, *result_2);
		}
		
	}else if(*operador =='x'){
		multiplicacion_1_arg.x=x;
		multiplicacion_1_arg.y=y;
		result_3 = multiplicacion_1(&multiplicacion_1_arg, clnt);
		if (result_3 == (double *) NULL) {
			clnt_perror (clnt, "call failed");
		}else{
			printf(" RESULTADO \n %.2f x %.2f = %.2f\n ",x,y, *result_3);
		}
	
	}else if(*operador =='/'){
		division_1_arg.x=x;
		division_1_arg.y=y;
		result_4 = division_1(&division_1_arg, clnt);
		if (result_4 == (double *) NULL) {
			clnt_perror (clnt, "call failed");
		}else{
			printf(" RESULTADO \n %.2f / %.2f = %.4f\n ",x,y, *result_4);
		}
		
	}else{
		printf("Error coloca un operador valido: +,-,x,/ \n");
	}

	

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	double x,y;
	
	if (argc != 5) {
		printf ("Error, la sintaxis correcta es: host num1 Operador(+,-,x,/) num 2 \n");
		exit (1);
	}
	host = argv[1];

	if((x=atof(argv[2]))==0 && *argv[2]!='0'){
		fprintf(stderr,"invalid value:%s\n",argv[2]);
		exit(1);
	}
	if((y=atof(argv[4]))==0 && *argv[4]!='0'){
		fprintf(stderr,"invalid value:%s\n",argv[4]);
		exit(1);
	}


	calculadora_prog_1 (host,atof(argv[2]), argv[3], atof(argv[4]));
exit (0);
}
